pipeline {
    agent { label 'slave' }

    environment {
        DOCKER_DRIVER = 'overlay2'
        DOCKERHUB_USERNAME = 'tameemdevops'
        DOCKERHUB_IMAGE = "${DOCKERHUB_USERNAME}/blue-green"
        MICROK8S_PASSWORD = credentials('microk8')
        MICROK8S_USERNAME = 'root'
        MICROK8S_IP_ADDRESS = '137.184.65.39'
    }

    stages {
        stage('Build Blue') {
            steps {
                sh '''
                /kaniko/executor \
                  --context `pwd` \
                  --dockerfile `pwd`/Dockerfile \
                  --destination docker.io/${DOCKERHUB_IMAGE}:Blue
                '''
            }
        }

        stage('Build Green') {
            steps {
                sh '''
                /kaniko/executor \
                  --context `pwd` \
                  --dockerfile `pwd`/Dockerfile \
                  --destination docker.io/${DOCKERHUB_IMAGE}:Green
                '''
            }
        }

        stage('Deploy to MicroK8s') {
            steps {
                sh '''
                apk add --no-cache openssh sshpass
                sshpass -p "$MICROK8S_PASSWORD" scp -o StrictHostKeyChecking=no k8s/*.yml ${MICROK8S_USERNAME}@${MICROK8S_IP_ADDRESS}:/home/${MICROK8S_USERNAME}/k8s
                sshpass -p "$MICROK8S_PASSWORD" ssh -o StrictHostKeyChecking=no ${MICROK8S_USERNAME}@${MICROK8S_IP_ADDRESS} "cd /home/${MICROK8S_USERNAME}/k8s && microk8s.kubectl apply -f ."
                '''
            }
        }
    }
}
